DEEPSORT:
  MODEL_TYPE: "resnet50"
  MAX_DIST: 0.1 # The matching threshold. Samples with larger distance are considered an invalid match
  MAX_IOU_DISTANCE: 0.99 # Gating threshold. Associations with cost larger than this value are disregarded.
  MAX_AGE: 100 # Maximum number of missed misses before a track is deleted
  N_INIT: 3 # Number of frames that a track remains in initialization phase
  NN_BUDGET: 10000 # Maximum size of the appearance descriptors gallery
  
